name: WebCam Gauge Sensor
slug: webcam_gauge_sensor
description: Read an analog gauge from RTSP and publish the value to MQTT.
version: "0.1.1"
url: https://github.com/Zergie/HomeAssistant-WebCam-Sensor
arch:
  - aarch64
  - amd64
  - armv7
  - i386
startup: services
boot: auto
init: false
services:
  - mqtt:want
options:
  rtsp_url: ""
  x: 835
  y: 400
  radius: 350
  rotate: 0.0
  sharpen: 8.0
  points:
    - "0.0,-150,210"
    - "1.0,-197,280"
    - "1.5,-227,280"
    - "2.0,95,275"
    - "2.5,57,275"
    - "3.0,25,275"
    - "4.0,-32,230"
  poll_interval: 60
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_topic: "sensors/boiler_pressure"
schema:
  rtsp_url: str
  x: int
  y: int
  radius: int
  rotate: float
  sharpen: float
  points:
    - str
  poll_interval: int
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str?
  mqtt_password: password?
  mqtt_topic: str
